name: Deploy to Itch.io

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: zip
        run: zip -r dist.zip dist

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: deploy
        run: echo "${GITHUB_REF#refs/*/}"
      # - name: deploy
      #   uses: josephbmanley/butler-publish-itchio-action@b5f0b072e8b12b731c69f12b5430f594700e0947
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     VERSION: "${GITHUB_REF#refs/*/}"
      #     ITCH_USER: ${{ secrets.ITCH_USER }}
      #     ITCH_GAME: ${{ secrets.ITCH_GAME }}
      #     PACKAGE: dist.zip
      #     CHANNEL: web
