name: Deploy to Itch.io

on:
  push:
    tags:
      - v*

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.vars.outputs.artifact-id }}
      itch-user: ${{ vars.ITCH_USER || github.repository_owner }}
      itch-game: ${{ vars.ITCH_GAME }}
    steps:
      - name: setup vars
        id: vars
        run: |
          echo "artifact-id=dist-${GITHUB_REF#refs/*/}.zip" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: zip
        run: zip -r dist.zip dist

      - name: upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.setup.outputs.artifact-id }}
          path: dist.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - setup
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.setup.outputs.artifact-id }}

      - name: deploy
        uses: josephbmanley/butler-publish-itchio-action@b5f0b072e8b12b731c69f12b5430f594700e0947
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          VERSION: "${GITHUB_REF#refs/*/}"
          ITCH_USER: ${{ needs.setup.outputs.itch-user }}
          ITCH_GAME: ${{ needs.setup.outputs.itch-game }}
          CHANNEL: web
